### ISSUE TITLE
error when a student saves a new submission

### ISSUE THREAD

**Issue by tkimnguyen** [OshkoshScholars/uwosh.oshkoshscholars#11]
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 117, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 100, in handleAdd
  Module z3c.form.form, line 250, in createAndAdd
  Module plone.dexterity.browser.add, line 75, in add
  Module plone.dexterity.utils, line 185, in addContentToContainer
  Module Products.BTreeFolder2.BTreeFolder2, line 455, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module uwosh.oshkoshscholars.events, line 85, in event_submission_added
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by tkimnguyen** [comment]
Fixed in https://github.com/OshkoshScholars/uwosh.oshkoshscholars/commit/f90275c2d59f8dc5c6dfe336fa7561cba8981ac5

**Comment by gutow** [comment]
It's still happening.  See error log entries: https://oshkoshscholar.brianledwell.com/prefs_error_log_showEntry?id=1463669530.370.354790887001
and https://oshkoshscholar.brianledwell.com/prefs_error_log_showEntry?id=1463669216.560.68352291352

Or am I just ahead of the fixes migrating from code to the site?

**Comment by gutow** [comment]
The link/button definitely works if you start logged in as student bill.

**Comment by tkimnguyen** [comment]
That error message is gone. If you can, please paste it directly in here.

**Comment by gutow** [comment]
Did we do something to clear them?  I cannot get it either anymore.  I will try to reproduce it and generate a new error.

**Comment by gutow** [comment]
Just regenerated the error.  It is now number 1463756778.120.8395538182.  However, it is a different type now.  It used to be a 'NoneType' error. Now is it "UnboundLocalError".

**Comment by tkimnguyen** [comment]
The error logs get cleared when the instance gets restarted, which happens frequently since this is under development.

**Comment by tkimnguyen** [comment]
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 117, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 100, in handleAdd
  Module z3c.form.form, line 250, in createAndAdd
  Module plone.dexterity.browser.add, line 75, in add
  Module plone.dexterity.utils, line 185, in addContentToContainer
  Module Products.BTreeFolder2.BTreeFolder2, line 455, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module uwosh.oshkoshscholars.events, line 92, in event_submission_added
UnboundLocalError: local variable 'faculty_id1' referenced before assignment
```
